### ISSUE TITLE
Responsividade do Site 

### ISSUE THREAD

**Issue by glaucia86** [zenorocha/zenorocha.com#26]
Oi Zeno. Tudo certo?
Fiz um fork do seu projeto. E fiz algumas alterações para o meu site pessoal (que por sinal ficou muito legal: https://glaucialemos.netlify.com/

Porém agora, tou querendo tratar a questão da responsividade. Vi que você usou a lib que vocês criaram, o senna.js
Cheguei a dar uma olhada nesse arquivo. Mas, acredito que a responsividade terei que tratar no main.css
Você tem dicas em como deixar esse projeto de maneira responsiva, pensando no mobile first?

cc: @zenorocha

**Comment by zenorocha** [comment]
Parabéns pelo projeto! Muito legal ver esse fork.

O senna.js é utilizado para navegação (SPA), com relação a responsividade seria no CSS mesmo.

Uma curiosidade que eu tenho é com relação a qual parte de responsividade que não tá funcionando pra você porque no zenorocha.com parece tudo correto.

**Comment by glaucia86** [comment]
Conforme a imagem abaixo, quando eu coloco no modo de visualização para mobile, note que a imagem não redimensiona e a nav também. Até pensei que poderia ser algo do próprio metalsmith. Mas, depois de fazer algumas pesquisas vi que precisa alterar as medias queries no css. Cheguei até alterar, porém sem sucesso.
Se você entrar no meu site e colocar no modo mobile, vai ver que ele não fica responsivo.. e não consigo entender o porquê.... 

Link: https://glaucialemos.netlify.com/

![image](https://user-images.githubusercontent.com/1631477/52761326-17d9f400-2ffa-11e9-8811-38e42958e5b6.png)

Também gostei demais do projeto. Para a versão 2 implementarei internacionalização nele (assim como no site do nodejs.org, que também faz uso do metalsmith e trabalha muito bem com o internacionalização. Tenho ajudado o pessoal do time do nodejs foundation e do react community tbm.)

cc: @zenorocha
